// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfdHL9l25FsfjsOBUOfyoRdbKSuPI1bik',
    appId: '1:49495820436:web:f9b1fce479fd37420d8c81',
    messagingSenderId: '49495820436',
    projectId: 'vault-app-b1b78',
    authDomain: 'vault-app-b1b78.firebaseapp.com',
    storageBucket: 'vault-app-b1b78.firebasestorage.app',
    measurementId: 'G-HDYXG6TRR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjpHN7cWQIsiNA2RdkYcetVXz4wVu6eKY',
    appId: '1:49495820436:android:88d1692210e877120d8c81',
    messagingSenderId: '49495820436',
    projectId: 'vault-app-b1b78',
    storageBucket: 'vault-app-b1b78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAefNeBsySaXz-LihkjYOBPfxg75SAQ6xs',
    appId: '1:49495820436:ios:bdecefdaa70d90c10d8c81',
    messagingSenderId: '49495820436',
    projectId: 'vault-app-b1b78',
    storageBucket: 'vault-app-b1b78.firebasestorage.app',
    iosBundleId: 'com.example.vaultApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAefNeBsySaXz-LihkjYOBPfxg75SAQ6xs',
    appId: '1:49495820436:ios:bdecefdaa70d90c10d8c81',
    messagingSenderId: '49495820436',
    projectId: 'vault-app-b1b78',
    storageBucket: 'vault-app-b1b78.firebasestorage.app',
    iosBundleId: 'com.example.vaultApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfdHL9l25FsfjsOBUOfyoRdbKSuPI1bik',
    appId: '1:49495820436:web:941f366f483100da0d8c81',
    messagingSenderId: '49495820436',
    projectId: 'vault-app-b1b78',
    authDomain: 'vault-app-b1b78.firebaseapp.com',
    storageBucket: 'vault-app-b1b78.firebasestorage.app',
    measurementId: 'G-ERG7QC1MWS',
  );
}
